---
title: "Blokus Simulation 2"
author: "Rui Qiang"
date: "12/9/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

#mydata = read.csv("BigFirst1PossMoves", col.names = "x", sep = "")
#mydata = scan("BigFirst1PossMoves", what = "character")
mydata = read_lines("BigFirst1PossMoves", skip = 0, n_max = 100)
MatrixList = list(NULL)
#for( i in 1:nrow(mydata)){
#  entries = suppressWarnings(as.numeric(strsplit(as.character(mydata$x[i]), #"")[[1]])[1:400])
#  new_matrix = matrix(entries, nrow = 20, ncol = 20, byrow = T)
#  MatrixList[[i]] = new_matrix
#}


analyze.possible.moves = function(mydata){
  PlayerList = list()
  PlayerList[[1]] = rep(0,21)
  PlayerList[[2]] = rep(0,21)
  PlayerList[[3]] = rep(0,21)
  PlayerList[[4]] = rep(0,21)
  for(i in 1:length(mydata)){
  current.data = noquote(strsplit(mydata[i], "")[[1]])
  player.count = rep(0,4)
  # extract data and reformat
  size = length(current.data)
  for(j in 1:size){
    if(current.data[j] == ":"){
      k = j+1
      entry = 0
      player = as.numeric(current.data[j-1])
      player.count[player] = player.count[player] + 1
      while(current.data[k] != ","){
        entry = entry*10 + as.numeric(current.data[k])
        k = k + 1
      }
      PlayerList[[player]][player.count[player]] = PlayerList[[player]][player.count[player]]+ entry
    }
  }
  }
  return(PlayerList)
}


######## Analyzing the Possible Moves

# The code below computes the average number of possible moves a player has at each round of the game. mean values derived from 100 simulations 
overall.result = analyze.possible.moves(mydata)
player1.summary = (overall.result[[1]])/length(mydata)
player2.summary = (overall.result[[2]])/length(mydata)
player3.summary = (overall.result[[3]])/length(mydata)
player4.summary = (overall.result[[4]])/length(mydata)

# The function below computes the percentage of increase/decrease the number of possible moves
droporincrease = function(myvector){
  last = length(myvector)
  while(last!=1){
    diff = myvector[last] - myvector[last-1]
    if(myvector[last-1] != 0){
      myvector[last] = diff/myvector[last-1]
    }
    last = last - 1
  }
  myvector[1] = 0
  return(myvector)
}

# The code below computes the percentage of increase/decrease of number of possible moves

player1.summary = droporincrease(player1.summary)
player2.summary = droporincrease(player2.summary)
player3.summary = droporincrease(player3.summary)
player4.summary = droporincrease(player4.summary)

# The code below is an analysis of chances of winning at each stage when we assume that the chance of winning is directly proportional to number of possible moves
overall.summary = player1.summary + player2.summary + player3.summary + player4.summary
player1.summary = player1.summary/overall.summary
player2.summary = player2.summary/overall.summary
player3.summary = player3.summary/overall.summary
player4.summary = player4.summary/overall.summary
# The plot below has x and y range adjusted for percentage
plot(player1.summary, col = 5, type = "l",lwd = 1, ylab = "Number of Possible Moves", xlab = "Round", main = "Number of Possible Moves at Each Round of the game", ylim = c(-1,4), xlim = c(1,22))
lines(player2.summary, col = 2, lwd = 1)
lines(player3.summary, col = 3, lwd = 1)
lines(player4.summary, col = 4, lwd = 1)
legend(10, 3, c("player1","player2","player3", "player4"), cex=0.8, 
   col=c(5, 2, 3, 4), lty= 1)
########




comparison = matrix(nrow = 4, ncol = 4)
who_win = c(0, 0, 0, 0)
comparison[is.na(comparison)] = 0

for( i in 1:nrow(mydata)){
  temp = table(MatrixList[[i]])
  if(i == 1){
    sum = temp
  }else{
    sum = sum + temp
  }
  win = which.max(as.matrix(temp)[2:5])
  lose = which.min(as.matrix(temp)[2:5])
  comparison[win, lose] = comparison[win, lose] + 1
  who_win[win] = who_win[win] + 1
  #image(MatrixList[[i]], col = c(0, 2, 7, 4, 3))
}

print(comparison)
print(who_win)
overall1 = matrix(rep(0,400), nrow = 20)
overall2 = overall1
overall3 = overall2
overall4 = overall3
#image(MatrixList[[29]], col = c(0, 2, 7, 4, 3))
for( i in 1:100){
  for( a in 1:20){
    for(b in 1:20){
      if((MatrixList[[i]])[a,b] == 1){
        overall1[a,b] = overall1[a,b] + 1
      }else if(MatrixList[[i]][a,b] == 2){
        overall2[a,b] = overall2[a,b] + 1
      }else if(MatrixList[[i]][a,b] == 3){
        overall3[a,b] = overall3[a,b] + 1
      }else if(MatrixList[[i]][a,b] == 4){
        overall4[a,b] = overall4[a,b] + 1
      }
    }
  }
}
#overall = overall/10
levelplot(overall1)
levelplot(overall2)
levelplot(overall3)
levelplot(overall4)
levelplot(t(overall3))
levelplot(overall2)
comp23 = overall2 - t(overall3)
levelplot(comp23)

```

```{}
Conclusions:
Question: Number of possible moves at the player's turn?
Maximum number of possible moves occur at around round 5.
The whole curve looks like a beta distribution. (Need some validation and some explaination though)
Outcome of the game with the given strategy(Big piece first) is only determined at round 12/13 when possible moves are much more restricted, and order of placing pieces plays is a huge determining factor

Something wrong with player 4. First step should be 58 possible moves.
After move number 15, group12's winning chance starts increasing, where as group34's winning chance starts to declining. This is a good indication that the order for which players place their pieces starts to become the major factor. 
```
